background {
    monitor =
    path = screenshot # Or "screenshot" to use a screenshot of the desktop
    color = rgba(0, 0, 0, 1.0) # Fallback color if path is empty or image is not found
    blur_passes = 2
    blur_size = 7
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    outer_color = rgb(151515)
    inner_color = rgb(200, 200, 200)
    font_color = rgb(10, 10, 10)
    placeholder_text = <i>Input Password...</i>
}
