set-option -g status-position top

set-option -g status-bg "#363a4f"
set-option -g status-fg "#cad3f5"

set -g status-left ""
set-option -g status-left-length 0

set -g @active_window_color "#cad3f5"
set -g @inactive_window_color "#939ab7"

set -g @window_fg '#363a4f'

set -g window-status-format '#[bg=#{@inactive_window_color},fg=#{@window_fg}] #I #[fg=#{status-fg},bg=#494d64] #W #[fg=#494d64,bg=#{status-bg}]#[default]'
set -g window-status-current-format '#[bg=#{@active_window_color},fg=#{@window_fg}] #I #[fg=#{status-fg},bg=#494d64] #W #[fg=#494d64,bg=#{status-bg}]#[default]'

set -g @prefix_color "#ed8796"

set -g @clock_bg '#949ab7'
set -g @clock_fg '#363a4f'

set -g status-right \
"\#{?window_zoomed_flag, ,} "\
"#[fg=#{@clock_bg}]#[fg=#{@clock_fg},bg=#{@clock_bg}] %l:%M %p "\
"#[fg=#{?client_prefix,#{@prefix_color},#{status-fg}}]#[fg=#363a4f]#[bg=#{?client_prefix,#{@prefix_color},#{status-fg}}] #S "

# Making the bar transparent
set-option -g status-style bg=default
