###########
# General #
###########
set-option -g status-position top

set -g @prefix_color "#f5a97f"

set -g @session_fg "#363a4f"
set -g @session_bg "#cad3f5"

set -g @git_fg "#363a4f"
set -g @git_bg "#939ab7"

set -g @window_fg "#cad3f5"
set -g @current_window_fg "#a6da95"

set-option -g status-bg "default"
set-option -g status-fg "#cad3f5"

# Making the bar transparent
set-option -g status-style bg=default

#########################
# Left and Right Status #
#########################

set -g status-left-length 120
set -g status-left \
"#[fg=#{@session_fg}]#[bg=#{?client_prefix,#{@prefix_color},#{@session_bg}}]"\
" #S  "\
"#[bg=#{status-bg},fg=#{?client_prefix,#{@prefix_color},#{@session_bg}}]"

set -g status-right-length 120
set -g status-right \
"#($HOME/.config/tmux/scripts/battery.sh) "\
"\#{?window_zoomed_flag,#[fg=#{@prefix_color}]#[fg=#{@session_fg}]#[bg=#{@prefix_color}] ,}"\
"#[fg=#{?client_prefix,#{@prefix_color},#{@session_bg}}]#[fg=#{@session_fg}]#[bg=#{?client_prefix,#{@prefix_color},#{@session_bg}}]"\
" %I:%M %p "

###########
# Windows #
###########

# Moving Window Status to the Middle
set -g status-justify absolute-centre

set -g window-status-format '#[fg=#{?client_prefix,#{@prefix_color},#{@window_fg}}] #W'
set -g window-status-current-format '#[fg=#{?client_prefix,#{@prefix_color},#{@current_window_fg}}] '\
'#[fg=#{?client_prefix,#{@prefix_color},#{@window_fg}}]#W'
