# Rebind splits (Inverted binds)
unbind '"'
unbind '%'
bind v split-window -h
bind h split-window -v

# Force naming of new windows (I'm lazy...)
unbind c
bind c command-prompt -p "Window name:" "new-window; rename-window %%"

# Replacing session switching with projman
unbind "s"
bind s popup -E "projman active -p tmux"

# Break current pane out into window
bind ! command-prompt -p "Window name:" "break-pane -t : \; rename-window '%%'"

# Join panes in a split
bind-key H choose-window 'join-pane -v -s "%%"'
bind-key V choose-window 'join-pane -h -s "%%"'

# Reload config
bind r source ~/.config/tmux/tmux.conf

# Launch applications in new window
bind -n C-y popup -h 75% -w 75% -E "yazi"
bind -n C-g "new-window 'lazygit'; rename-window 'Lazygit'"
bind -n C-t popup -h 75% -w 75% -E "$SHELL"

bind -n C-p popup -E "projman -p tmux"
bind -n C-s popup -E "projman active -p tmux"

# Apply coding layout: 80-column main pane with vertical split
bind L run-shell 'if [ $(tmux list-panes | wc -l) -eq 1 ]; then tmux split-window -h; fi && tmux set-window-option main-pane-width 80 && tmux select-layout main-vertical'

bind g run-shell 'if [ "$(tmux show-option -gqv @show_git_branch_short)" = "0" ]; then tmux set -g @show_git_branch_short 1; else tmux set -g @show_git_branch_short 0; fi; tmux refresh-client -S'

bind q kill-pane
bind Q kill-session

# Click session name in status-right to switch sessions
bind-key -T root MouseDown1StatusLeft display-popup -E 'projman active -p tmux'
