# Enabling Mouse support
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Setting vim bindings for selection mode
setw -g mode-keys vi

# Fixing colours
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Stop autorenmaing
set-window-option -g automatic-rename off

# Setting bar to refresh every 5 seconds
set -g status-interval 5

# Yazi Configuration
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

set -g @show_git_branch_short 0
